In [2]:
import tensorflow as tf

In [3]:
tf.VERSION

'1.5.0'

In [4]:
print(tf.__version__)

1.5.0


In [5]:
hello=tf.constant("Hello ")

In [6]:
world=tf.constant("World")

In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess0:
    result= sess0.run(hello + world)

In [10]:
print(result)

Hello World


In [12]:
a = tf.constant(10)
b = tf.constant(20)

In [13]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [14]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
a-b

<tf.Tensor 'sub:0' shape=() dtype=int32>

In [17]:
with tf.Session() as sess:
    Res= sess.run(a+b)

In [18]:
Res

30

In [19]:
print(Res)

30


In [20]:
const=tf.constant(10)

In [38]:
fill_mat = tf.fill((3,3),11)  #3 by 3 fill with 11
fill_mat

<tf.Tensor 'Fill_11:0' shape=(3, 3) dtype=int32>

In [45]:
myzeros = tf.zeros((3,3))

In [46]:
myones = tf.ones((3,3))

In [47]:
myrandn = tf.random_normal((3,3), mean=0, stddev=1.0)

In [48]:
myrandu = tf.random_uniform((3,3),minval=0, maxval=1)

In [49]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu] #list of all operations

In [58]:
with tf.Session() as sess: #One way OR ...interactive session for Jupyter Notebook just...
    for op in my_ops:
     R1= sess.run(op)  #OR op.eva()
     print (R1)
     print('\n')

10


[[11 11 11]
 [11 11 11]
 [11 11 11]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[ 0.9381873  -1.1519091   0.10693341]
 [ 0.53364754  0.5567215   0.25639442]
 [-1.8347929  -0.43159384 -1.2526848 ]]


[[0.42238545 0.64997554 0.5123435 ]
 [0.391495   0.6800628  0.4792273 ]
 [0.724843   0.984583   0.71715546]]




In [56]:
print(R1)

[[0.84758854 0.6370919  0.7627704 ]
 [0.96202147 0.9598763  0.50538087]
 [0.07444799 0.16875482 0.96679044]]


In [59]:
sess02 = tf.InteractiveSession() #interactive session for Jupyter Notebook jus

In [60]:
for op in my_ops:
    print(sess02.run(op))
    print('\n')

10


[[11 11 11]
 [11 11 11]
 [11 11 11]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[-0.11074483  0.32281965 -0.6102554 ]
 [-0.7405889   0.8740979  -0.6215766 ]
 [ 0.0979491   0.74125844  0.81849355]]


[[0.6624273  0.5936208  0.02855682]
 [0.21558559 0.14417493 0.94911623]
 [0.41879642 0.40613532 0.97835314]]




In [62]:
a =tf.constant([[1,2],   #Matrixes..., Multiply,...
               [3,4]])

In [63]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [64]:
b = tf.constant([[10],[100]])

In [65]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [67]:
c= tf.matmul(a,b)
sess02.run(c)  #Because of defining Interactive session! with no with

array([[210],
       [430]], dtype=int32)

In [68]:
c.eval()

array([[210],
       [430]], dtype=int32)