In [1]:
import tensorflow as tf

In [3]:
sess = tf.InteractiveSession()

In [4]:
my_tensor = tf.random_uniform((4,4),0,1)

In [6]:
my_tensor

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [12]:
sess.run(my_tensor)

array([[0.36766982, 0.58592033, 0.3803115 , 0.3289261 ],
       [0.28383517, 0.02318311, 0.5788194 , 0.8818437 ],
       [0.5341203 , 0.4240917 , 0.6310227 , 0.9202497 ],
       [0.07413113, 0.84895813, 0.84162176, 0.2804247 ]], dtype=float32)

Variables:::

In [13]:
my_var = tf.Variable(initial_value=my_tensor)

In [14]:
print(my_var)

<tf.Variable 'Variable_1:0' shape=(4, 4) dtype=float32_ref>


In [16]:
# sess.run(my_var)...............Note! You must initialize all global variables!

In [21]:
# This line is really important, it is easy to forget!
init=tf.global_variables_initializer()

In [26]:
sess.run(init)

In [25]:
sess.run(my_var)

array([[0.28721058, 0.674814  , 0.35771513, 0.06960607],
       [0.8584484 , 0.54111433, 0.8040743 , 0.2724296 ],
       [0.82189393, 0.48040712, 0.80196726, 0.13820529],
       [0.92715406, 0.64843154, 0.5355873 , 0.8409326 ]], dtype=float32)

In [27]:
my_var.eval()

array([[0.41251552, 0.43987274, 0.42424464, 0.5010178 ],
       [0.35406756, 0.6741469 , 0.12262094, 0.9160291 ],
       [0.06272662, 0.29110038, 0.25439143, 0.72907627],
       [0.00513387, 0.7748271 , 0.13413095, 0.7253287 ]], dtype=float32)

In [28]:
ph=tf.placeholder(tf.float32)

In [29]:
# For shape its common to use (None,# of Features) 
# because None can be filled by number of samples in data
ph = tf.placeholder(tf.float32,shape=(None,5))

In [31]:
print(ph)

Tensor("Placeholder_1:0", shape=(?, 5), dtype=float32)
